version: "3.8"

networks:
  backend:

services:

  # WEB SERVER
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: web_server
    ports:
      - '8000:80'
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - backend

  # LANGUAGE FOR WEB DEVELOPMENT
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - backend

  # RELATIONAL DATABASE MANAGEMENT SYSTEM
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./env/mysql.env
    networks:
      - backend

  # DEPENDENCY MANAGER FOR JAVASCRIPT
  npm:
    image: node:latest
    container_name: npm
    working_dir: /var/www/html
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www/html
      -
  # DEPENDENCY MANAGER FOR PHP
    networks:
      - backend

  composer:
    container_name: composer
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - backend

  # COMMAND LINE INTERFACE
  artisan:
    container_name: artisan
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php","/var/www/html/artisan" ]
    networks:
      - backend

